/**
 * PWA Events and Commands Constants
 * Shared between app and service worker for structured communication via BroadcastChannel
 */

// Commands sent from app to service worker
export const COMMANDS = {
    ACTIVATE_DATA_CACHING: 'ACTIVATE_DATA_CACHING',
    DEACTIVATE_DATA_CACHING: 'DEACTIVATE_DATA_CACHING',
    CACHE_STATUS: 'CACHE_STATUS',
    CACHE_DATA_ALL: 'CACHE_DATA_ALL',
    CACHE_DATA_PRESENTATION: 'CACHE_DATA_PRESENTATION',
    NUKE_DATA: 'NUKE_DATA'
};

// Events sent from service worker to app
export const EVENTS = {
    STATUS: 'STATUS',
    DATA_CACHING_PROGRESS: 'DATA_CACHING_PROGRESS',
    DATA_CACHING_PRESENTATION_PROGRESS: 'DATA_CACHING_PRESENTATION_PROGRESS',
    DATA_CACHING_PRESENTATION_COMPLETE: 'DATA_CACHING_PRESENTATION_COMPLETE',
    DATA_CACHING_COMPLETE: 'DATA_CACHING_COMPLETE',
    CONTENT_REFRESH_RECOMMENDED: 'CONTENT_REFRESH_RECOMMENDED',
    NUKE_DATA_COMPLETE: 'NUKE_DATA_COMPLETE'
};

// Broadcast channel name
export const CHANNEL_NAME = 'pwa-events';
